### ISSUE TITLE
Using scipy's genetic algorithm for curve fitting

### ISSUE THREAD

**Issue by zunzun** [allantargino/GeneticLib#1]
I have used scipy's Differential Evolution genetic algorithm to find initial parameters for fitting a double Lorentzian peak equation to Raman spectroscopy data. I found that the results were excellent, and see from your GitHub project that you might find my project to be interesting.

The GitHub project, with a test spectroscopy data file, is:

https://github.com/zunzun/RamanSpectroscopyFit

If you have any questions, let me know and I will be glad to help.

James Phillips

**Comment by allantargino** [comment]
Hi James, thanks for the recommendation. We are going to implement a generic library to handle genetic algorithms problems, like the one you have solved. Thanks again.
